#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
VERSION="${1:-0.1.0}"
OUTPUT_DIR="${2:-${SOURCE_DIR}/dist}"
BUILD_DIR="${3:-${SOURCE_DIR}/build/linux-release}"

mkdir -p "${OUTPUT_DIR}"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd)"
STAGE_DIR="$(mktemp -d /tmp/arcadeblocks2-pacman.XXXXXX)"

echo "==> Staging pacman package files in ${STAGE_DIR}..."
DESTDIR="${STAGE_DIR}" cmake --install "${BUILD_DIR}" --prefix /usr

INSTALLED_SIZE=$(du -sb "${STAGE_DIR}" | awk '{print $1}')
BUILD_DATE=$(date +%s)

cat << PKGINFO > "${STAGE_DIR}/.PKGINFO"
# Generated by ArcadeBlocks II
pkgname = arcadeblocks2
pkgbase = arcadeblocks2
pkgver = ${VERSION}-1
pkgdesc = Native C++ foundation for Arcade Blocks II
url = https://github.com/leocallidus/arcadeblocks2
builddate = ${BUILD_DATE}
packager = leocallidus <leoalekseev27@gmail.com>
size = ${INSTALLED_SIZE}
arch = x86_64
license = custom
PKGINFO

PKG_FILE="${OUTPUT_DIR}/arcadeblocks2-${VERSION}-1-x86_64.pkg.tar.zst"
echo "==> Creating Arch Linux package: ${PKG_FILE}..."
(
    cd "${STAGE_DIR}"
    tar --zstd -cf "${PKG_FILE}" .PKGINFO usr
)

rm -rf "${STAGE_DIR}"
echo "==> Successfully built ${PKG_FILE}"
